name: SimpleWarp
main: com.cruzbishop.simplewarp.SimpleWarp
version: 1.0.0
website: https://github.com/CruzBishop/SimpleWarp
author: Cruz Bishop
database: true
description: >
             Basic warp functionality
commands:
  listwarps:
    aliases: [warplist]
    description: Lists the available warps
    usage: |
           /<command>
           Example: /<command>
  addwarp:
    aliases: [createwarp, makewarp]
    description: Adds a new warp point
    usage: |
           /<command> <name>
           Example: /<command> <name>
  removewarp:
    aliases: [deletewarp, dwarp]
    description: Removes a warp point
    usage: |
           /<command> <name>
           Example: /<command> <name>
  warp:
    aliases: [usewarp, wrp]
    description: Warps to the specified warp point
    usage: |
           /<command> <name>
           Example: /<command> <name>